import { StyleSheet } from "react-native";
export const C = {
  ink0: "#0A0A0B",
  ink50: "#18181B",
  ink100: "#27272A",
  ink200: "#3F3F46",
  ink300: "#52525B",
  ink400: "#71717A",
  ink500: "#A1A1AA",
  brand300: "#FB923C",
  brand400: "#F97316",
  brand500: "#F97316",
  brand600: "#EA580C",
  white: "#FFFFFF",
};

export const styles = StyleSheet.create({
  logoWrap: {
    alignItems: "center",
    marginTop: 44,
    marginBottom: 16,
  },
  logoContainer: {
    width: 140,
    height: 140,
    alignItems: "center",
    justifyContent: "center",
  },
  halo: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: C.brand500,
  },
  ring: {
    position: "absolute",
    width: 112,
    height: 112,
    borderRadius: 56,
    borderWidth: 2,
    borderColor: C.brand400,
  },
  chargeRing: {
    position: "absolute",
    width: 128,
    height: 128,
    borderRadius: 64,
    borderWidth: 2,
    borderColor: "transparent",
    borderTopColor: C.brand300,
    borderRightColor: C.brand400,
  },
  chargeDot: {
    position: "absolute",
    top: -4,
    left: 60,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: C.brand300,
  },
  bolt: {
    width: 92,
    height: 92,
    borderRadius: 46,
    backgroundColor: C.ink50,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: C.brand500,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 24,
    elevation: 10,
  },
  titleWrap: {
    alignItems: "center",
    marginTop: 22,
  },
  brand: {
    fontSize: 30,
    fontWeight: "700",
    color: C.white,
    fontFamily: "Inter-Bold",
    letterSpacing: -0.5,
  },
  subtitle: {
    fontSize: 14,
    color: C.ink400,
    marginTop: 6,
    fontFamily: "Inter-Regular",
  },
});
