import { C } from "@/src/theme";
import { StyleSheet } from "react-native";

export const notificationStyles = StyleSheet.create({
  root: { flex: 1 },
  flex: { flex: 1 },

  header: {
    paddingHorizontal: 20,
    paddingTop: 14,
    paddingBottom: 14,
    backgroundColor: C.ink50,
    borderBottomWidth: 1,
    borderBottomColor: C.ink200,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 26,
    fontWeight: "700",
    color: C.white,
    fontFamily: "Inter-Bold",
    letterSpacing: -0.3,
  },
  headerSubtitle: {
    fontSize: 13,
    color: C.ink400,
    fontFamily: "Inter-Regular",
    marginTop: 2,
  },
  headerGlow: {
    position: "absolute",
    bottom: -1,
    left: 0,
    right: 0,
    height: 3,
    backgroundColor: C.brand400,
    shadowColor: C.brand400,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 8,
  },
  markAllBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: C.ink100,
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1.5,
    borderColor: C.ink200,
  },
  markAllText: {
    fontSize: 12,
    color: C.brand400,
    fontWeight: "600",
    fontFamily: "Inter-SemiBold",
  },

  pullIndicator: {
    position: "absolute",
    top: 130,
    left: 0,
    right: 0,
    alignItems: "center",
    zIndex: 10,
  },
  pullInner: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: C.ink50,
    borderWidth: 2,
    borderColor: C.brand400,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: C.brand500,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.5,
    shadowRadius: 16,
    elevation: 8,
  },

  card: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.ink50,
    borderRadius: 0,
    borderBottomWidth: 1,
    borderBottomColor: C.ink200,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  cardUnread: {
    backgroundColor: C.ink100,
  },
  iconBox: {
    width: 46,
    height: 46,
    borderRadius: 14,
    alignItems: "center",
    justifyContent: "center",
  },
  cardBody: {
    flex: 1,
    marginLeft: 12,
    marginRight: 8,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  unreadDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: C.brand400,
    shadowColor: C.brand400,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 4,
  },
  cardTitle: {
    fontSize: 14,
    fontWeight: "700",
    color: C.white,
    fontFamily: "Inter-Bold",
    flexShrink: 1,
  },
  cardMessage: {
    fontSize: 12,
    color: C.ink400,
    fontFamily: "Inter-Regular",
    marginTop: 4,
    lineHeight: 17,
  },
  dateBox: {
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.ink100,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 5,
    minWidth: 42,
  },
  dateDay: {
    fontSize: 13,
    fontWeight: "700",
    color: C.ink300,
    fontFamily: "Inter-Bold",
    lineHeight: 15,
  },
  dateMonth: {
    fontSize: 8,
    fontWeight: "600",
    color: C.ink500,
    fontFamily: "Inter-SemiBold",
    lineHeight: 10,
  },
  chevron: {
    marginLeft: 6,
  },

  endText: {
    textAlign: "center",
    fontSize: 12,
    color: C.ink500,
    fontFamily: "Inter-SemiBold",
    marginTop: 20,
  },

  swipeWrap: {
    position: "relative",
    marginBottom: 0,
  },
  deleteBg: {
    position: "absolute",
    top: 0,
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: C.error,
    borderRadius: 0,
    alignItems: "flex-end",
    justifyContent: "center",
    paddingRight: 24,
  },
  emptyWrap: {
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
    gap: 12,
  },
  emptyText: {
    fontSize: 14,
    color: C.ink500,
    fontFamily: "Inter-SemiBold",
  },
});
